import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of use",
  description: "Terms of use for ScorelineIQ.",
};

export default function TermsPage() {
  return (
    <article className="flex max-w-2xl flex-col gap-4 text-sm leading-relaxed text-zinc-700">
      <h1 className="text-2xl font-semibold tracking-tight text-zinc-950">Terms of use</h1>

      <p>Last updated: this is an early, pre-launch version of the site and these terms will be reviewed before public launch.</p>

      <h2 className="mt-2 text-lg font-semibold text-zinc-950">Statistical analysis, not advice</h2>
      <p>
        All predictions, probabilities, and statistics on ScorelineIQ are generated by an
        automated statistical model for informational and entertainment purposes only. They are
        not betting advice, financial advice, or a guarantee of any match outcome. Football
        results are inherently uncertain.
      </p>

      <h2 className="mt-2 text-lg font-semibold text-zinc-950">No liability</h2>
      <p>
        We make no warranty as to the accuracy or completeness of any content on this site, and we
        aren&apos;t liable for any decisions made, or losses incurred, based on it. Our public{" "}
        <a href="/accuracy" className="underline">accuracy record</a> reflects real historical
        performance, not a promise of future results.
      </p>

      <h2 className="mt-2 text-lg font-semibold text-zinc-950">Third-party links</h2>
      <p>
        This site may link to third-party bookmakers or other sites. We don&apos;t control and
        aren&apos;t responsible for their content, terms, or availability.
      </p>

      <h2 className="mt-2 text-lg font-semibold text-zinc-950">Intellectual property</h2>
      <p>
        The site design, model, and written content are ours. Team names, crests, and competition
        names referenced are the property of their respective owners and are used for identification
        purposes only.
      </p>

      <h2 className="mt-2 text-lg font-semibold text-zinc-950">Changes</h2>
      <p>We may update these terms as the site develops. Continued use of the site means you accept the current version.</p>
    </article>
  );
}
